# DocumentLens Docker Compose
# Australian Document Analysis Microservice

version: '3.8'

services:
  documentlens:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      # Production configuration
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=4
      
      # File processing limits
      - MAX_FILE_SIZE=52428800  # 50MB
      - MAX_FILES_PER_REQUEST=10
      
      # Rate limiting (Australian-friendly)
      - RATE_LIMIT=30/minute
      
      # CORS - update for your domain
      - ALLOWED_ORIGINS=*
      
      # Security - CHANGE IN PRODUCTION
      - SECRET_KEY=change-this-secret-key-in-production
      
    volumes:
      # Optional: Mount logs directory
      - ./logs:/app/logs
      
      # Optional: Mount for persistent NLTK data
      - ./data:/app/data
      
    restart: unless-stopped
    
    # Resource limits (adjust based on your VPS)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
      
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # For SSL certificates
    depends_on:
      - documentlens
    restart: unless-stopped
    profiles:
      - production  # Only start with: docker-compose --profile production up
      
networks:
  default:
    name: documentlens_network