/**
 * Screenshot manifest for the help system — which captured screen belongs to
 * which help topic, with its caption.
 *
 * Files live in docs/screenshots/ and are regenerated by
 * `npm run capture:help` (scripts/capture-help-screenshots.mjs drives the
 * real app). The PDF manual embeds every entry; the in-app help shows only
 * entries with `inApp: true` — the app is already on screen there, so images
 * earn their place only where words struggle (the visual workflows).
 *
 * Pure data on purpose: this module is imported by both the Vite renderer
 * and the node-side manual exporter.
 */

export interface HelpScreenshot {
  /** File name inside docs/screenshots/. */
  file: string
  caption: string
  /** Also show inside the in-app Help page (PDF always includes it). */
  inApp?: boolean
}

export const HELP_SCREENSHOTS: Record<string, HelpScreenshot[]> = {
  'getting-started': [
    {
      file: 'wizard.png',
      caption: 'The three-step first-run wizard — name, focus, documents, defaults.',
    },
    {
      file: 'overview.png',
      caption: 'The project Overview: every workflow as the question it answers.',
    },
  ],
  setup: [
    {
      file: 'setup.png',
      caption: 'The Setup tab assembles documents, keyword list, lenses, and scoring rule.',
    },
  ],
  coverage: [
    {
      file: 'coverage.png',
      caption: 'Coverage: documents × keywords heatmaps, positive matches above counter matches.',
      inApp: true,
    },
  ],
  map: [
    {
      file: 'map.png',
      caption: 'Map: how keyword usage distributes across lens axes.',
      inApp: true,
    },
  ],
  read: [
    { file: 'read.png', caption: 'Read: each keyword match in its surrounding context.' },
  ],
  discover: [
    {
      file: 'discover.png',
      caption: 'Discover: phrases and synonyms the corpus uses that your list may be missing.',
    },
  ],
  score: [
    { file: 'score.png', caption: 'Score: each document rated on the chosen rubric, with the why.' },
  ],
  track: [
    { file: 'track.png', caption: 'Track: the metric across years.' },
  ],
  compare: [
    { file: 'compare.png', caption: 'Compare: documents ranked on the chosen metric.' },
  ],
  audit: [
    { file: 'audit.png', caption: 'Audit: is each keyword used in the right context?' },
  ],
  gap: [
    {
      file: 'gap.png',
      caption: 'Gap: sentiment against keyword substance — tone running ahead of delivery.',
      inApp: true,
    },
  ],
}
