import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Sparkles, Loader2, AlertTriangle } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { Button } from '@/components/ui/button'
import type { ObserveResult } from '@/services/ai-observations'

/**
 * Reusable panel for the (optional) AI-observation features. It runs the given
 * observe function and renders the result, always clearly flagged as
 * AI-generated and non-repeatable. Errors about a missing provider link to
 * Settings.
 */
export function AiObservationsPanel({
  label,
  onRun,
}: {
  label: string
  onRun: () => Promise<ObserveResult>
}) {
  const [running, setRunning] = useState(false)
  const [result, setResult] = useState<ObserveResult | null>(null)

  const run = async () => {
    setRunning(true)
    setResult(null)
    try {
      setResult(await onRun())
    } catch (err) {
      setResult({ ok: false, error: err instanceof Error ? err.message : String(err) })
    } finally {
      setRunning(false)
    }
  }

  const noProvider = result && !result.ok && /active AI provider|model selected|configure/i.test(result.error ?? '')

  return (
    <div className="border border-border rounded-md p-4">
      <div className="flex items-center justify-between gap-3 mb-2 flex-wrap">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-violet-500" />
          <span className="font-medium text-sm">AI observations</span>
          <span className="text-[10px] uppercase tracking-wide bg-violet-500/10 text-violet-600 dark:text-violet-300 rounded px-1.5 py-0.5">
            AI-generated
          </span>
        </div>
        <Button size="sm" variant="outline" onClick={run} disabled={running} className="gap-1.5">
          {running ? (
            <><Loader2 className="h-4 w-4 animate-spin" /> Thinking…</>
          ) : (
            <><Sparkles className="h-4 w-4" /> {result ? 'Regenerate' : label}</>
          )}
        </Button>
      </div>
      <p className="text-xs text-muted-foreground mb-3">
        An initial interpretation of the deterministic signals by your configured AI provider. It
        varies between runs and is <strong>not a repeatable signal</strong> — treat it as a pointer,
        not a finding.
      </p>

      {result?.ok && result.text && (
        <div>
          <div className="text-sm [&_ul]:list-disc [&_ul]:pl-5 [&_ol]:list-decimal [&_ol]:pl-5 [&_li]:mt-1 [&_p]:mt-2 [&_h1]:font-medium [&_h2]:font-medium [&_h3]:font-medium [&_strong]:font-semibold">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{result.text}</ReactMarkdown>
          </div>
          {(result.provider || result.model) && (
            <p className="text-[11px] text-muted-foreground mt-3 italic">
              Generated by {result.provider}
              {result.model ? ` · ${result.model}` : ''}. AI-generated — verify against the source.
            </p>
          )}
        </div>
      )}

      {result && !result.ok && (
        <p className="text-sm text-destructive flex items-start gap-1.5">
          <AlertTriangle className="h-4 w-4 shrink-0 mt-0.5" />
          <span>
            {result.error}
            {noProvider && (
              <>
                {' '}<Link to="/settings" className="underline">Configure a provider</Link>.
              </>
            )}
          </span>
        </p>
      )}
    </div>
  )
}
