#!/usr/bin/env node
/**
 * Generate the Rust database registry from the TypeScript source of truth.
 *
 * Decision (TAURI-MIGRATION-PLAN.md §3.1): `electron/schema.ts` and
 * `electron/queries.ts` stay the single source of truth — the renderer's
 * vitest suite runs that exact SQL against in-memory better-sqlite3. Rather
 * than hand-port the registry to Rust (and let the two drift), this script
 * emits `src-tauri/src/db_generated.rs` from the TS. Re-run after any change
 * to the schema or query registry:  `npm run gen:rust-db`
 *
 * The generated file is committed so `cargo build` never needs Node. CI should
 * run this and `git diff --exit-code` to catch drift.
 *
 * Imports the .ts modules directly via Node's type-stripping (Node 22.18+),
 * which works because both files use only erasable syntax and import nothing.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const here = path.dirname(fileURLToPath(import.meta.url))
const repo = path.resolve(here, '..')

const { SCHEMA, SCHEMA_VERSION } = await import(
  path.join(repo, 'electron', 'schema.ts')
)
const { QUERIES, UPDATABLE_COLUMNS } = await import(
  path.join(repo, 'electron', 'queries.ts')
)

// JSON.stringify of ASCII SQL yields a string literal that is valid Rust too
// (escapes ", \, \n identically; our SQL has no \b/\f/unicode). Reused for
// every embedded SQL string.
const rustStr = (s) => JSON.stringify(s)

const queryArms = Object.entries(QUERIES)
  .map(([key, sql]) => `        ${rustStr(key)} => Some(${rustStr(sql)}),`)
  .join('\n')

const columnArms = Object.entries(UPDATABLE_COLUMNS)
  .map(([table, cols]) => {
    const list = [...cols].map(rustStr).join(', ')
    return `        ${rustStr(table)} => Some(&[${list}]),`
  })
  .join('\n')

const out = `// @generated by scripts/gen-rust-db.mjs — DO NOT EDIT.
// Source of truth: electron/schema.ts + electron/queries.ts.
// Regenerate with: npm run gen:rust-db
#![allow(clippy::all)]

/// Schema version. A mismatch on disk triggers a wipe-and-recreate (greenfield;
/// no migrations) — see db.rs.
pub const SCHEMA_VERSION: i64 = ${SCHEMA_VERSION};

/// Full DDL, applied verbatim at init. Identical bytes to the Electron path.
pub const SCHEMA: &str = ${rustStr(SCHEMA)};

/// Resolve a registry key to its SQL. The security boundary: the renderer sends
/// a key, never SQL, so it can only invoke queries that exist here.
pub fn query(key: &str) -> Option<&'static str> {
    match key {
${queryArms}
        _ => None,
    }
}

/// Per-table column allowlist for dynamic partial UPDATEs (see build_update).
pub fn updatable_columns(table: &str) -> Option<&'static [&'static str]> {
    match table {
${columnArms}
        _ => None,
    }
}
`

const dest = path.join(repo, 'src-tauri', 'src', 'db_generated.rs')
writeFileSync(dest, out)
console.log(
  `[gen-rust-db] wrote ${path.relative(repo, dest)} — ` +
    `${Object.keys(QUERIES).length} queries, ${Object.keys(UPDATABLE_COLUMNS).length} updatable tables, schema v${SCHEMA_VERSION}`,
)
