#!/usr/bin/env node
/**
 * Tauri launcher — keeps Cargo's `target/` off the project drive.
 *
 * This repo lives on an exFAT volume. exFAT can't store extended attributes,
 * so macOS writes an AppleDouble `._<name>` sidecar beside every file. Tauri's
 * build.rs globs its generated permissions dir and tries to parse those
 * sidecars as TOML, which hard-fails the build:
 *
 *   failed to define permissions for core:path: failed to read file
 *   '…/permissions/path/autogenerated/._default.toml':
 *   stream did not contain valid UTF-8
 *
 * Redirecting CARGO_TARGET_DIR to the internal disk sidesteps it entirely, and
 * is worth it regardless: Rust writes hundreds of thousands of small files into
 * target/, which exFAT handles far more slowly than APFS.
 *
 * `.cargo/config.toml` can't express this (its target-dir takes no env
 * expansion, and an absolute path would be machine-specific), so it lives here.
 * An explicit CARGO_TARGET_DIR in the environment always wins — CI can set its
 * own without fighting this script.
 */
import { spawn } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

const targetDir =
  process.env.CARGO_TARGET_DIR ??
  path.join(os.homedir(), '.cache', 'document-lens-tauri-target')

fs.mkdirSync(targetDir, { recursive: true })

const tauriBin = path.join(
  process.cwd(),
  'node_modules',
  '.bin',
  process.platform === 'win32' ? 'tauri.cmd' : 'tauri',
)

const child = spawn(tauriBin, process.argv.slice(2), {
  stdio: 'inherit',
  env: { ...process.env, CARGO_TARGET_DIR: targetDir },
})

child.on('exit', (code, signal) => {
  if (signal) process.kill(process.pid, signal)
  else process.exit(code ?? 0)
})
