#!/usr/bin/env node
/**
 * Tauri launcher — keeps Cargo's `target/` off the project drive.
 *
 * This repo lives on an exFAT volume. exFAT can't store extended attributes,
 * so macOS writes an AppleDouble `._<name>` sidecar beside every file. Tauri's
 * build.rs globs its generated permissions dir and tries to parse those
 * sidecars as TOML, which hard-fails the build:
 *
 *   failed to define permissions for core:path: failed to read file
 *   '…/permissions/path/autogenerated/._default.toml':
 *   stream did not contain valid UTF-8
 *
 * Redirecting CARGO_TARGET_DIR to the internal disk sidesteps it entirely, and
 * is worth it regardless: Rust writes hundreds of thousands of small files into
 * target/, which exFAT handles far more slowly than APFS.
 *
 * `.cargo/config.toml` can't express this (its target-dir takes no env
 * expansion, and an absolute path would be machine-specific), so it lives here.
 * An explicit CARGO_TARGET_DIR in the environment always wins — CI can set its
 * own without fighting this script.
 */
import { spawn } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

const targetDir =
  process.env.CARGO_TARGET_DIR ??
  path.join(os.homedir(), '.cache', 'document-lens-tauri-target')

fs.mkdirSync(targetDir, { recursive: true })

/**
 * Sweep AppleDouble sidecars out of the Tauri source tree.
 *
 * Redirecting CARGO_TARGET_DIR keeps `._*` files out of target/, but Tauri's
 * build.rs also globs directories that live in the *source* tree — notably
 * `capabilities/` — and parses every entry it finds:
 *
 *   failed to read file 'capabilities/._default.json':
 *   stream did not contain valid UTF-8
 *
 * On exFAT those sidecars reappear whenever macOS writes extended attributes,
 * so this runs before every invocation rather than as a one-off cleanup.
 * Deleting them is safe: they carry only xattrs/resource forks, never source.
 *
 * The durable fix is moving the repo to an APFS volume; this keeps the build
 * green until then.
 */
function sweepAppleDouble(dir) {
  let removed = 0
  const walk = (current) => {
    let entries
    try {
      entries = fs.readdirSync(current, { withFileTypes: true })
    } catch {
      return // unreadable dir — nothing to sweep
    }
    for (const entry of entries) {
      const full = path.join(current, entry.name)
      if (entry.isDirectory()) {
        if (entry.name === 'target' || entry.name === 'node_modules') continue
        walk(full)
      } else if (entry.name.startsWith('._')) {
        try {
          fs.unlinkSync(full)
          removed++
        } catch {
          /* best effort */
        }
      }
    }
  }
  walk(dir)
  return removed
}

if (process.platform === 'darwin') {
  const removed = sweepAppleDouble(path.join(process.cwd(), 'src-tauri'))
  if (removed > 0) {
    console.log(`[tauri] swept ${removed} AppleDouble ._* file(s) from src-tauri/`)
  }
}

const tauriBin = path.join(
  process.cwd(),
  'node_modules',
  '.bin',
  process.platform === 'win32' ? 'tauri.cmd' : 'tauri',
)

const child = spawn(tauriBin, process.argv.slice(2), {
  stdio: 'inherit',
  env: { ...process.env, CARGO_TARGET_DIR: targetDir },
})

child.on('exit', (code, signal) => {
  if (signal) process.kill(process.pid, signal)
  else process.exit(code ?? 0)
})
